name: BuildingGame
author: CutesMouse
version: "1.3.2"
api-version: "1.21.11"
description: "Building Game"
main: com.cutesmouse.bdgame.Main
depend:
  - "MGui"
  - "WorldEdit"
commands:
  buildinggame:
    usage: "The main command for Building Game by Mouse"
    aliases:
      - "bg"
      - "bd"
      - "bdgame"
  query:
    usage: "Query Game Status"
    aliases:
      - q
  pastebuilding:
    usage: "Paste record buildings into current room"
    aliases:
      - pb
      - lookup
  request:
    usage: "Chat message trigger"